export const UPDATE_CONTACT_API_ENDPOINT =
  process.env.REACT_APP_UPDATE_CONTACT_API_ENDPOINT || "";
export const GET_FTR_EVENTS_SIGN_UPS =
  process.env.REACT_APP_GET_FTR_EVENTS_SIGN_UP_COUNTS || "";
export const GET_FTR_EVENTS_MASTER_SIGN_UPS =
  process.env.REACT_APP_GET_FTR_EVENTS_MASTER_COUNTS || "";

export default UPDATE_CONTACT_API_ENDPOINT;
