openapi: 3.1.0
info:
  title: Contact Email API
  version: 1.0.0
  description: API for sending contact emails with detailed error handling.
  contact:
    name: Justin Makaila
    email: justin@treehousetechnology.io
servers:
  - url: /api
    description: Production server
tags:
  - name: Contact Email
    description: Operations related to sending contact emails
paths:
  /email:
    post:
      description: Submits an email from the contact form to the configured email address.
      operationId: email-post
      summary: Submits an email from the contact form to the configured email address.
      tags:
        - Contact Email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactEmail'
      responses:
        '201':
          description: Email sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request - Input validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ContactEmail:
      type: object
      required:
        - name
        - email
        - message
      properties:
        name:
          type: string
          description: Name of the sender
        email:
          type: string
          format: email
          description: Email address of the sender
        message:
          type: string
          description: Message content
      example:
        name: John Doe
        email: john.doe@example.com
        message: Hello, I have a question.
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: Success message
      example:
        message: Email sent
    ValidationErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
        details:
          type: object
          description: Detailed error information from Zod
      example:
        error: Invalid parameters provided.
        details:
          name: Name is required.
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
        details:
          type: string
          description: Detailed error information
      example:
        error: Internal Server Error
        details: Unknown